"""Initial migration with fixed relationships ver2

Revision ID: 2734dfcc585b
Revises: 2a6d0459b118
Create Date: 2025-10-26 01:34:30.864410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2734dfcc585b'
down_revision: Union[str, Sequence[str], None] = '2a6d0459b118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
