"""Initial migration

Revision ID: 52bf081d92db
Revises: e78a712d53fe
Create Date: 2025-10-25 23:33:21.712703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bf081d92db'
down_revision: Union[str, Sequence[str], None] = 'e78a712d53fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_progress')
    )
    op.create_index(op.f('ix_course_progress_course_id'), 'course_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_progress_user_id'), 'course_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_materials_module_id'), 'materials', ['module_id'], unique=False)
    op.add_column('question_attempts', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_test_question_attempt', 'question_attempts', ['test_attempt_id', 'question_id', 'attempt_number'])
    op.add_column('test_attempts', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('test_attempts', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.create_index('idx_user_test_attempt', 'test_attempts', ['user_id', 'test_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_user_id'), 'test_attempts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'test_attempts', 'questions', ['current_question_id'], ['id'], ondelete='SET NULL')
    op.drop_column('test_attempts', 'attempts_count')
    op.create_index(op.f('ix_tests_material_id'), 'tests', ['material_id'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tests_material_id'), table_name='tests')
    op.add_column('test_attempts', sa.Column('attempts_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_test_attempts_user_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_index('idx_user_test_attempt', table_name='test_attempts')
    op.drop_column('test_attempts', 'current_question_id')
    op.drop_column('test_attempts', 'attempt_number')
    op.drop_constraint('uq_test_question_attempt', 'question_attempts', type_='unique')
    op.drop_column('question_attempts', 'attempt_number')
    op.drop_index(op.f('ix_materials_module_id'), table_name='materials')
    op.drop_index(op.f('ix_course_progress_user_id'), table_name='course_progress')
    op.drop_index(op.f('ix_course_progress_course_id'), table_name='course_progress')
    op.drop_table('course_progress')
    # ### end Alembic commands ###
