"""Add text type to material_type enum

Revision ID: 8261e0c11f62
Revises: 3c3d053fa1aa
Create Date: 2025-11-07 04:14:46.673002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8261e0c11f62'
down_revision: Union[str, Sequence[str], None] = '3c3d053fa1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE material_type ADD VALUE 'text'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
