"""Add test_attempt_feedback table

Revision ID: 8c4382cc8efb
Revises: 8261e0c11f62
Create Date: 2026-01-18 18:57:46.398493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4382cc8efb'
down_revision: Union[str, Sequence[str], None] = '8261e0c11f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_attempt_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_attempt_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False, comment='Персонализированная рекомендация студенту'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_attempt_feedbacks_id'), 'test_attempt_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_test_attempt_feedbacks_test_attempt_id'), 'test_attempt_feedbacks', ['test_attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_attempt_feedbacks_test_attempt_id'), table_name='test_attempt_feedbacks')
    op.drop_index(op.f('ix_test_attempt_feedbacks_id'), table_name='test_attempt_feedbacks')
    op.drop_table('test_attempt_feedbacks')
    # ### end Alembic commands ###
